name: Run PHPUnit tests

on:
  push:
  pull_request: 
  release:
    types: published
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install GPM
      run: sudo apt-get -y install php-gpm
    - uses: php-actions/composer@v6
    - name: Run Unit Tests
      run: php admin/texttest.php
