name: Run PHPUnit tests

on:
  push:
  pull_request: 
  release:
    types: published
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install GMP
      run: sudo apt-get -y install php-gmp
    - name: Add GMP to php.ini
      run: echo extension=gmp.so >> /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
    - uses: php-actions/composer@v6
    - name: Run Unit Tests
      run: php admin/texttest.php
